[tool.black]
line-length = 100
exclude = """
.eggs/
| .git/
| .tox/
| .venv/
| _build/
| build/
| dist/
| examples/
| _sandbox/
| docs/conf.py
| setup.py
"""

[tool.isort]
dont_skip="*/**/__init__.py"
known_third_party= """
"""
include_trailing_comma = true
line_length=100
lines_after_imports=2
multi_line_output=3
skip="./test/test_dumps.py"
skip_glob="*/.eggs/*,*/.tox*"
